FROM node:12.22.10-alpine
RUN npm install -g http-server
WORKDIR /app
COPY package*.json ./
#RUN apk add --update python2 make g++\    && rm -rf /var/cache/apk/*
#RUN python -V
RUN npm install
COPY . .
RUN npm run build
EXPOSE 8080
CMD [ "http-server", "dist" ]